name: DevOps Normal Change

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ServiceNowDevOpsChange:
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Change (Prod Deploy)

    steps:
    # -----------------------------------
    # CHECKOUT
    # -----------------------------------
    - name: Checkout
      uses: actions/checkout@v4

    # -----------------------------------
    # CREATE DEVOPS NORMAL CHANGE
    # -----------------------------------
    - name: Create ServiceNow Normal Change
      id: CreateChange
      uses: ServiceNow/servicenow-devops-change@v6.1.0
      with:
        devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER_DEMO14 }}
        devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD_DEMO14 }}
        instance-url: ${{ secrets.SN_INSTANCE_URL_DEMO14 }}
        tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID_DEMO14 }}
        context-github: ${{ toJSON(github) }}
        job-name: "ServiceNow DevOps Change (Prod Deploy)"
        change-request: >
          {
            "attributes": {
              "short_description": "DevOps Normal Change GH",
              "description": "Production change\nTests successful",
              "requested_by": "a0e11bb23ba32300b200655593efc491"
            }
          }

        interval: "15"
        timeout: "900"
